import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Announcment from "./components/Announcment";
// import Countdown from "./components/CountDown";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const eventDate = '2024-12-31T00:00:00'; 

  return (
    <html lang="en">
      <body className={inter.className}>
        <Announcment />
        <Navbar />
        {children}
        {/* <Countdown eventDate={eventDate} /> */}
      </body>
    </html>
  );
}
